document.addEventListener('DOMContentLoaded', () => { if (!localStorage.getItem('arisePlayerState')) { showAwakening(); } else { initializeApp(); } });
let playerState = { name: 'Hunter', level: 1, xp: 0, xpToNextLevel: 100, arks: 0, rank: 'E', rankPoints: 0, rankPointsToNext: 500, completedMissionsToday: [], completedGatesToday: [], shadowArmy: [], equippedWeapon: null, equippedSkill: null, xpMultiplier: 1, shadowFragments: 0, dailyMissions: [], inventory: [], weeklyChallenge: null, lastWeeklyResetDate: null, equippedShadowId: null, };
let gateTimer = null, gateSeconds = 0, awakeningStep = 0;
const RANKS = ['E', 'D', 'C', 'B', 'A', 'S'];
const EXERCISE_DB = [ { id: 'pushups', name: 'Flexões', unit: 'reps', icon: 'fa-hand-rock' }, { id: 'squats', name: 'Agachamentos', unit: 'reps', icon: 'fa-dumbbell' }, { id: 'plank', name: 'Prancha', unit: 'segundos', icon: 'fa-stopwatch' }, { id: 'jumping_jacks', name: 'Polichinelos', unit: 'reps', icon: 'fa-child' }, { id: 'lunges', name: 'Afundos', unit: 'reps', icon: 'fa-walking' }, { id: 'run', name: 'Corrida Leve', unit: 'minutos', icon: 'fa-running' }, ];
const MISSION_TEMPLATES = [ { type: 'reps', baseValue: 10, variance: 5, xpBase: 15, arksBase: 8 }, { type: 'time', baseValue: 30, variance: 15, xpBase: 10, arksBase: 5 }, ];
const LOOT_TABLES = { mission: [{ type: 'arks', min: 5, max: 15, chance: 0.7 }, { type: 'xp', min: 10, max: 25, chance: 0.6 }, { type: 'shadow_fragment', amount: 1, chance: 0.05 }, { type: 'mystery_box', amount: 1, chance: 0.02 }], gate: [{ type: 'arks', min: 20, max: 40, chance: 0.8 }, { type: 'xp', min: 40, max: 80, chance: 0.9 }, { type: 'shadow_fragment', amount: 1, chance: 0.1 }, { type: 'mystery_box', amount: 1, chance: 0.05 }], boss: [{ type: 'arks', min: 80, max: 120, chance: 1.0 }, { type: 'xp', min: 180, max: 250, chance: 1.0 }, { type: 'shadow_fragment', amount: 3, chance: 0.5 }, { type: 'mystery_box', amount: 2, chance: 0.2 }], };
const GATES_DATA = [ { id: 'g1', name: 'Portão de Treinamento: Corpo Inferior', xpReward: 50, arksReward: 25, description: 'Foco em pernas e glúteos.', difficulty: 'Fácil', icon: 'fa-shoe-prints' }, { id: 'g2', name: 'Portão de Treinamento: Força Bruta', xpReward: 60, arksReward: 30, description: 'Foco em peito e costas.', difficulty: 'Médio', icon: 'fa-fist-raised' }, { id: 'gBoss', name: 'Portão Chefe: Monarca do HIIT', xpReward: 200, arksReward: 100, description: 'Treino intervalado de alta intensidade.', difficulty: 'Difícil', isBoss: true, icon: 'fa-skull-crossbones' }, ];
const SHADOWS_DATA = [ { id: 's1', name: 'Soldado', bonus: '+2% XP em Missões', source: 'g1', icon: 'fa-shield-alt', bonusType: 'xp_percentage', bonusValue: 0.02 }, { id: 's2', name: 'Igris', bonus: '+5% Arks em Portões', source: 'gBoss', icon: 'fa-khanda', bonusType: 'arks_percentage', bonusValue: 0.05 }, ];
const SHOP_ITEMS = [ { id: 'potion1', name: 'Poção de EXP Pequena', cost: 50, effect: () => { gainRewards(100, 0); }, description: 'Ganha 100 XP instantaneamente.', icon: 'fa-flask' }, { id: 'potion2', name: 'Poção de Arks Pequena', cost: 25, effect: () => { gainRewards(0, 50); }, description: 'Ganha 50 Arks instantaneamente.', icon: 'fa-gem' }, { id: 'boost1', name: 'Boost de Treinamento (1 uso)', cost: 150, effect: () => { playerState.xpMultiplier = 2; addSystemLog("[SISTEMA] Boost de 2x XP ativado para o próximo Portão."); }, description: 'Dobra o XP do próximo Portão concluído.', icon: 'fa-rocket' }, ];
const WEEKLY_CHALLENGE_TEMPLATES = [ { type: 'total_reps', target: 500, description: 'Complete 500 repetições (Flexões, Agachamentos, etc.) esta semana.', reward: { type: 'shadow', id: 's1' } }, { type: 'total_time', target: 120, description: 'Acumule 120 minutos de treino (Corrida, Prancha, etc.) esta semana.', reward: { type: 'arks', amount: 300 } }, { type: 'gate_completions', target: 10, description: 'Limpe 10 Portões esta semana.', reward: { type: 'mystery_box', amount: 5 } }, ];
const EVENT_GATE_DATA = { name: 'Portão de Evento: Dimensão Fissurada', description: 'Uma anomalia espaço-temporal! Dificuldade extrema, recompensas lendárias.', xpReward: 350, arksReward: 200, difficulty: 'Impossível', icon: 'fa-vortex', isBoss: true };
const WORKOUT_PLANS_DB = [ { id: 'beginner_circuit', name: 'Circuito de Iniciante', difficulty: 'Fácil', exercises: [{ name: 'Agachamentos Livres', reps: 15 }, { name: 'Flexões de Joelho', reps: 10 }, { name: 'Prancha', time: 30 }, { name: 'Polichinelos', reps: 20 }] }, { id: 'core_strength', name: 'Força do Core', difficulty: 'Fácil', exercises: [{ name: 'Prancha', time: 45 }, { name: 'Elevação de Pélvis', reps: 20 }, { name: 'Abdominais', reps: 15 }, { name: 'Rosca Abdominal', time: 30 }] }, { id: 'hiit_burner', name: 'Queimador de HIIT', difficulty: 'Médio', exercises: [{ name: 'Burpees', reps: 10 }, { name: 'Mountain Climbers', time: 30 }, { name: 'Agachamentos com Salto', reps: 12 }, { name: 'Flexões', reps: 10 }, { name: 'Corrida no Lugar', time: 40 }] }, { id: 'upper_body_power', name: 'Poder do Corpo Superior', difficulty: 'Médio', exercises: [{ name: 'Flexões', reps: 15 }, { name: 'Flexões Diamante', reps: 8 }, { name: 'Dips na Cadeira', reps: 12 }, { name: 'Superman', reps: 15 }] }, { id: 'beast_mode', name: 'Modo Besta', difficulty: 'Difícil', exercises: [{ name: 'Burpees', reps: 20 }, { name: 'Flexões de Arqueiro', reps: 10 }, { name: 'Pistolas', reps: 8 }, { name: 'Prancha com Toque no Ombro', time: 60 }, { name: 'Explosões', reps: 15 }] }, { id: 'endurance_test', name: 'Teste de Resistência', difficulty: 'Difícil', exercises: [{ name: 'Corrida no Lugar', time: 90 }, { name: 'Agachamentos', reps: 50 }, { name: 'Flexões', reps: 40 }, { name: 'Prancha', time: 120 }] }, ];

function initializeApp() { loadGameState(); if (playerState.dailyMissions.length === 0) { generateDailyMissionsAI(); } if (playerState.weeklyChallenge === null) { generateWeeklyChallenge(); } checkForWeeklyReset(); updateUI(); updateMissionUI(); updateWeeklyChallengeUI(); generateGates(); generateShopItems(); addSystemLog("[SISTEMA] O Hunter está online."); }
function saveGameState() { localStorage.setItem('arisePlayerState', JSON.stringify(playerState)); }
function loadGameState() { const savedState = localStorage.getItem('arisePlayerState'); if (savedState) { try { playerState = { ...playerState, ...JSON.parse(savedState) }; } catch (e) { console.error("Failed to load saved state, resetting.", e); } } checkForDailyReset(); }
function checkForDailyReset() { const lastPlayed = localStorage.getItem('ariseLastPlayedDate'), today = new Date().toDateString(); if (lastPlayed !== today) { playerState.completedMissionsToday = []; playerState.completedGatesToday = []; playerState.dailyMissions = []; localStorage.setItem('ariseLastPlayedDate', today); addSystemLog("[SISTEMA] Novo dia detectado. A IA está gerando novas oportunidades.", true); } }
function checkForWeeklyReset() { const now = new Date(); const lastReset = playerState.lastWeeklyResetDate ? new Date(playerState.lastWeeklyResetDate) : null; if (!lastReset || now.getDay() < lastReset.getDay() || now.getDay() === 1) { playerState.weeklyChallenge = null; playerState.lastWeeklyResetDate = now.toDateString(); generateWeeklyChallenge(); addSystemLog("[SISTEMA] Nova semana, novo Desafio Semanal disponível!", true); } }

function updateUI() { updateHeaderUI(); document.getElementById('xp-text').textContent = `${playerState.xp} / ${playerState.xpToNextLevel}`; document.getElementById('arks-text').textContent = playerState.arks; const xpPercent = (playerState.xp / playerState.xpToNextLevel) * 100; document.getElementById('xp-bar').style.width = `${xpPercent}%`; document.getElementById('fragments-text').textContent = `${playerState.shadowFragments} / 10`; const fragmentsPercent = (playerState.shadowFragments / 10) * 100; document.getElementById('fragments-bar').style.width = `${fragmentsPercent}%`; updateRankProgressRing(); document.getElementById('daily-mission-count').textContent = playerState.completedMissionsToday.length; document.getElementById('total-mission-count').textContent = playerState.dailyMissions.length; document.getElementById('daily-gate-count').textContent = playerState.completedGatesToday.length; document.getElementById('equipped-weapon').textContent = playerState.equippedWeapon ? playerState.equippedWeapon.name : 'Nenhuma'; document.getElementById('equipped-skill').textContent = playerState.equippedSkill ? playerState.equippedSkill.name : 'Nenhuma'; const equippedShadow = playerState.shadowArmy.find(s => s.id === playerState.equippedShadowId); if (equippedShadow) { document.getElementById('equipped-shadow-name').textContent = equippedShadow.name; document.getElementById('equipped-shadow-bonus').textContent = `Bônus Ativo: ${equippedShadow.bonus}`; } else { document.getElementById('equipped-shadow-name').textContent = 'Nenhuma'; document.getElementById('equipped-shadow-bonus').textContent = 'Escolha uma sombra para receber seu bônus.'; } updateShadowArmyUI(); }
function updateHeaderUI() { document.getElementById('player-name').textContent = playerState.name; document.getElementById('player-rank').textContent = playerState.rank; document.getElementById('player-level').textContent = playerState.level; const powerLevel = calculatePowerLevel(); document.getElementById('player-power-level').textContent = powerLevel.toLocaleString('pt-BR'); }
function calculatePowerLevel() { const rankIndex = RANKS.indexOf(playerState.rank); const levelPower = playerState.level * 100; const rankPower = (rankIndex + 1) * 1000; const shadowPower = playerState.shadowArmy.length * 500; return levelPower + rankPower + shadowPower; }
function updateRankProgressRing() { const currentRankIndex = RANKS.indexOf(playerState.rank); playerState.rankPointsToNext = (currentRankIndex + 1) * 500; const rankPercent = Math.min((playerState.rankPoints / playerState.rankPointsToNext) * 100, 100); const circle = document.getElementById('rank-progress-ring-fill'), radius = circle.r.baseVal.value, circumference = radius * 2 * Math.PI; const offset = circumference - (rankPercent / 100) * circumference; circle.style.strokeDasharray = `${circumference} ${circumference}`; circle.style.strokeDashoffset = offset; document.getElementById('rank-percent').textContent = `${Math.floor(rankPercent)}%`; }
function showScreen(screenId) { document.querySelectorAll('.screen').forEach(s => s.classList.remove('active')); document.getElementById(screenId).classList.add('active'); }
function addSystemLog(message, isGlitch = false) { const log = document.getElementById('system-log'), p = document.createElement('p'); if(isGlitch) p.classList.add('glitch'); p.textContent = `> ${message}`; log.appendChild(p); log.scrollTop = log.scrollHeight; }
function showModal(title, body, footerContent) { document.getElementById('modal-title').innerHTML = title; document.getElementById('modal-body').innerHTML = body; document.getElementById('modal-footer').innerHTML = footerContent; document.getElementById('modal-container').style.display = 'block'; }
function hideModal() { document.getElementById('modal-container').style.display = 'none'; document.getElementById('modal-workout-list').innerHTML = ''; }
function showCelebration(title, message, isRankUp = false) { document.getElementById('celebration-title').textContent = title; document.getElementById('celebration-message').textContent = message; document.getElementById('celebration-overlay').style.display = 'flex'; if (isRankUp) { document.getElementById('new-rank-display').textContent = `Rank ${playerState.rank}`; document.getElementById('celebration-rank-up').style.display = 'block'; } else { document.getElementById('celebration-rank-up').style.display = 'none'; } }
function hideCelebration() { document.getElementById('celebration-overlay').style.display = 'none'; }
function showFloatingText(targetElement, text, type) { const floater = document.createElement('div'); floater.className = `floating-text ${type}`; floater.textContent = `+${text}`; const rect = targetElement.getBoundingClientRect(); floater.style.left = `${rect.left + rect.width / 2}px`; floater.style.top = `${rect.top}px`; document.body.appendChild(floater); setTimeout(() => floater.remove(), 2000); }

function generateWeeklyChallenge() { const template = WEEKLY_CHALLENGE_TEMPLATES[Math.floor(Math.random() * WEEKLY_CHALLENGE_TEMPLATES.length)]; playerState.weeklyChallenge = { ...template, progress: 0, claimed: false, }; saveGameState(); }
function updateWeeklyChallengeUI() { if (!playerState.weeklyChallenge) return; const challenge = playerState.weeklyChallenge; document.getElementById('weekly-challenge-description').textContent = challenge.description; const progressPercent = (challenge.progress / challenge.target) * 100; document.getElementById('weekly-challenge-progress').style.width = `${progressPercent}%`; document.getElementById('weekly-challenge-progress-text').textContent = `${challenge.progress} / ${challenge.target}`; const claimButton = document.getElementById('claim-weekly-reward'); if (challenge.progress >= challenge.target && !challenge.claimed) { claimButton.style.display = 'block'; } else { claimButton.style.display = 'none'; } }
function updateWeeklyChallengeProgress(amount, type) { if (!playerState.weeklyChallenge || playerState.weeklyChallenge.claimed) return; if (playerState.weeklyChallenge.type === type) { playerState.weeklyChallenge.progress += amount; if (playerState.weeklyChallenge.progress > playerState.weeklyChallenge.target) { playerState.weeklyChallenge.progress = playerState.weeklyChallenge.target; } updateWeeklyChallengeUI(); } }
function claimWeeklyReward() { const reward = playerState.weeklyChallenge.reward; if (reward.type === 'arks') { playerState.arks += reward.amount; } if (reward.type === 'mystery_box') { playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); } if (reward.type === 'shadow') { const shadowData = SHADOWS_DATA.find(s => s.id === reward.id); if (!playerState.shadowArmy.find(s => s.id === reward.id)) { playerState.shadowArmy.push(shadowData); addSystemLog(`[SISTEMA] Recompensa do Desafio Semanal recebida! A Sombra de '${shadowData.name}' se juntou ao seu exército.`); } else { playerState.arks += 200; addSystemLog(`[SISTEMA] Recompensa do Desafio Semanal recebida! 200 Arks concedidos.`); } } playerState.weeklyChallenge.claimed = true; updateUI(); updateWeeklyChallengeUI(); saveGameState(); }

function equipShadow(shadowId) { if (playerState.shadowArmy.find(s => s.id === shadowId)) { playerState.equippedShadowId = shadowId; addSystemLog(`[SISTEMA] Sombra equipada. Bônus ativo.`); updateUI(); updateShadowArmyUI(); } }
function applyShadowBuffs(rewards) { const equippedShadow = playerState.shadowArmy.find(s => s.id === playerState.equippedShadowId); if (!equippedShadow) return rewards; let { xp, arks } = rewards; if (equippedShadow.bonusType === 'xp_percentage') { xp = Math.floor(xp * (1 + equippedShadow.bonusValue)); } if (equippedShadow.bonusType === 'arks_percentage') { arks = Math.floor(arks * (1 + equippedShadow.bonusValue)); } return { xp, arks }; }

function generateGates() { const gateList = document.getElementById('gate-list'); gateList.innerHTML = ''; if (Math.random() < 0.1) { const eventGate = { ...EVENT_GATE_DATA, id: 'event_gate_' + Date.now() }; const gateDiv = document.createElement('div'); gateDiv.className = 'gate-item card event-gate'; gateDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${eventGate.icon}"></i> ${eventGate.name} <span style="color: var(--warning-color)">(${eventGate.difficulty})</span></h4><p>${eventGate.description}</p><small><i class="fas fa-star"></i> ${eventGate.xpReward} XP | <i class="fas fa-gem"></i> ${eventGate.arksReward} Arks</small></div><button onclick="enterGate('${eventGate.id}')">Entrar</button>`; gateList.appendChild(gateDiv); } GATES_DATA.forEach(gate => { const isCompleted = playerState.completedGatesToday.includes(gate.id); const gateDiv = document.createElement('div'); gateDiv.className = 'gate-item card'; if (gate.isBoss) gateDiv.style.borderColor = 'var(--danger-color)'; gateDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${gate.icon}"></i> ${gate.name} <span style="color: ${gate.difficulty === 'Fácil' ? 'var(--success-color)' : gate.difficulty === 'Médio' ? 'var(--warning-color)' : 'var(--danger-color)'}">(${gate.difficulty})</span></h4><p>${gate.description}</p><small><i class="fas fa-star"></i> ${gate.xpReward} XP | <i class="fas fa-gem"></i> ${gate.arksReward} Arks</small></div><button onclick="enterGate('${gate.id}')" ${isCompleted ? 'disabled' : ''}>Entrar</button>`; gateList.appendChild(gateDiv); }); }
function generateShopItems() { const shopList = document.getElementById('shop-items'); shopList.innerHTML = ''; const dailyDealIndex = Math.floor(Math.random() * SHOP_ITEMS.length); SHOP_ITEMS.forEach((item, index) => { const isDailyDeal = index === dailyDealIndex; const finalCost = isDailyDeal ? Math.floor(item.cost * 0.75) : item.cost; const canAfford = playerState.arks >= finalCost; const itemDiv = document.createElement('div'); itemDiv.className = `shop-item card ${isDailyDeal ? 'daily-deal' : ''}`; itemDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${item.icon}"></i> ${item.name}</h4><p>${item.description}</p><small><i class="fas fa-gem"></i> Custo: <s>${item.cost}</s> ${finalCost} Arks ${isDailyDeal ? '(25% OFF)' : ''}</small></div><button onclick="confirmItemPurchase('${item.id}', ${finalCost})" ${!canAfford ? 'disabled' : ''}>Comprar</button>`; shopList.appendChild(itemDiv); }); }
function confirmItemPurchase(itemId, cost) { const item = SHOP_ITEMS.find(i => i.id === itemId); const onConfirm = () => { playerState.arks -= cost; item.effect(); updateUI(); generateShopItems(); addSystemLog(`[SISTEMA] Você comprou '${item.name}'.`); hideModal(); }; showModal(`Confirmar Compra: ${item.name}`, `<p>Tem certeza que deseja comprar <strong>${item.name}</strong> por <strong>${cost} Arks</strong>?</p>`, `<button onclick="hideModal()">Cancelar</button><button class="btn-shop" onclick="onConfirm()" style="margin-left: 10px;">Comprar</button>`); }

function getWorkoutForDifficulty(difficulty) { const suitableWorkouts = WORKOUT_PLANS_DB.filter(plan => plan.difficulty === difficulty); if (suitableWorkouts.length === 0) return WORKOUT_PLANS_DB[0]; return suitableWorkouts[Math.floor(Math.random() * suitableWorkouts.length)]; }
function displayWorkout(workout, targetElementId) { const workoutListEl = document.getElementById(targetElementId); workoutListEl.innerHTML = ''; workout.exercises.forEach(exercise => { const itemEl = document.createElement('div'); itemEl.className = 'exercise-item'; let details = ''; if (exercise.reps) details = `${exercise.reps} reps`; if (exercise.time) details = `${exercise.time} seg`; if (exercise.reps_per_side) details = `${exercise.reps_per_side} reps (c/ lado)`; itemEl.innerHTML = `<span class="exercise-name">${exercise.name}</span><span class="exercise-details">${details}</span>`; workoutListEl.appendChild(itemEl); }); }

function generateDailyMissionsAI() { if (playerState.dailyMissions.length > 0) return; const missionCount = 4; for (let i = 0; i < missionCount; i++) { const template = MISSION_TEMPLATES[Math.floor(Math.random() * MISSION_TEMPLATES.length)]; const exercise = EXERCISE_DB[Math.floor(Math.random() * EXERCISE_DB.length)]; const levelScaling = 1 + (playerState.level * 0.1); let targetValue = Math.floor((template.baseValue + Math.floor(Math.random() * template.variance)) * levelScaling); let xpReward = Math.floor((template.xpBase + (targetValue * 0.1)) * levelScaling); let arksReward = Math.floor((template.arksBase + (targetValue * 0.05)) * levelScaling); const isSpecial = Math.random() < 0.1; if (isSpecial) { targetValue *= 2; xpReward *= 2.5; arksReward *= 2; } const difficulty = isSpecial ? 'Médio' : 'Fácil'; const workout = getWorkoutForDifficulty(difficulty); playerState.dailyMissions.push({ id: `ai_mission_${Date.now()}_${i}`, name: `${isSpecial ? '[S] ' : ''}${exercise.name}`, description: `Complete ${targetValue} ${exercise.unit}.`, xpReward: Math.floor(xpReward), arksReward: Math.floor(arksReward), icon: exercise.icon, isSpecial: isSpecial, workout: workout }); } saveGameState(); }
function updateMissionUI() { const missionList = document.getElementById('mission-list'); missionList.innerHTML = ''; if (playerState.dailyMissions.length === 0) { missionList.innerHTML = '<p>A IA está preparando suas missões para o dia.</p>'; return; } playerState.dailyMissions.forEach(mission => { const isCompleted = playerState.completedMissionsToday.includes(mission.id); const missionDiv = document.createElement('div'); missionDiv.className = `mission-item card ${isCompleted ? 'completed' : ''} ${mission.isSpecial ? 'special-mission' : ''}`; missionDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${mission.icon}"></i> ${mission.name}</h4><p>${mission.description}</p><small><i class="fas fa-star"></i> ${mission.xpReward} XP | <i class="fas fa-gem"></i> ${mission.arksReward} Arks</small></div><button onclick="completeMission('${mission.id}')" ${isCompleted ? 'disabled' : ''}>Completar</button>`; missionList.appendChild(missionDiv); }); }
function completeMission(missionId) { if (playerState.completedMissionsToday.includes(missionId)) return; const mission = playerState.dailyMissions.find(m => m.id === missionId); if (!mission) return; const workoutHtml = mission.workout ? `<div class="workout-display"><h4><i class="fas fa-clipboard-list"></i> Treino da Missão:</h4><ul id="modal-workout-list"></ul></div>` : ''; showModal(`Confirmar Missão: ${mission.name}`, `<p>Você realizou a tarefa: <strong>${mission.description}</strong>?</p>${workoutHtml}`, `<button onclick="hideModal()">Ainda não</button><button class="btn-reward" onclick="confirmMissionCompletion('${mission.id}')" style="margin-left: 10px;">Sim, Concluir!</button>`); if (mission.workout) { displayWorkout(mission.workout, 'modal-workout-list'); } }
function confirmMissionCompletion(missionId) { const mission = playerState.dailyMissions.find(m => m.id === missionId); if (!mission || playerState.completedMissionsToday.includes(missionId)) return; playerState.completedMissionsToday.push(mission.id); const loot = generateLoot('mission'); let totalXp = mission.xpReward, totalArks = mission.arksReward; loot.forEach(reward => { if (reward.type === 'xp') totalXp += reward.amount; if (reward.type === 'arks') totalArks += reward.amount; if (reward.type === 'shadow_fragment') playerState.shadowFragments += reward.amount; if (reward.type === 'mystery_box') playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); }); if (mission.unit === 'reps') updateWeeklyChallengeProgress(parseInt(mission.description.match(/\d+/)[0]), 'total_reps'); if (mission.unit === 'minutos' || mission.unit === 'segundos') updateWeeklyChallengeProgress(parseInt(mission.description.match(/\d+/)[0]), 'total_time'); gainRewards(totalXp, totalArks); addSystemLog(`Missão '${mission.name}' concluída. Recompensas: ${totalXp} XP, ${totalArks} Arks.`); hideModal(); updateUI(); updateMissionUI(); if (playerState.completedMissionsToday.length === playerState.dailyMissions.length) { document.getElementById('claim-daily-reward').style.display = 'block'; } }
function claimDailyReward() { gainRewards(50, 25); addSystemLog("[SISTEMA] Todas as missões diárias concluídas. Bônus concedido."); document.getElementById('claim-daily-reward').style.display = 'none'; saveGameState(); }
function enterGate(gateId) { let gate; if (gateId.startsWith('event_gate')) { gate = EVENT_GATE_DATA; } else { gate = GATES_DATA.find(g => g.id === gateId); } if (playerState.completedGatesToday.includes(gate.id)) { showModal("Portão Já Conquistado", `<p>Você já limpou este portão hoje. Volte amanhã para um novo desafio.</p>`, `<button onclick="hideModal()">Entendido</button>`); return; } showScreen('gate-active-screen'); document.getElementById('active-gate-name').textContent = gate.name; document.getElementById('active-gate-description').textContent = gate.description; const workout = getWorkoutForDifficulty(gate.difficulty); displayWorkout(workout, 'workout-list'); startGateTimer(); }
function startGateTimer() { gateSeconds = 0; updateGateTimerDisplay(); gateTimer = setInterval(() => { gateSeconds++; updateGateTimerDisplay(); }, 1000); }
function updateGateTimerDisplay() { const minutes = Math.floor(gateSeconds / 60), secs = gateSeconds % 60; document.getElementById('gate-timer').textContent = `${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`; }
function completeActiveGate() { clearInterval(gateTimer); const gateName = document.getElementById('active-gate-name').textContent; let gate; if (gateName.includes('Dimensão Fissurada')) { gate = EVENT_GATE_DATA; } else { gate = GATES_DATA.find(g => g.name === gateName); } playerState.completedGatesToday.push(gate.id); let xpGain = gate.xpReward; if (playerState.xpMultiplier > 1) { xpGain *= playerState.xpMultiplier; playerState.xpMultiplier = 1; addSystemLog("[SISTEMA] Boost de XP consumido.", true); } const lootSource = gate.isBoss ? 'boss' : 'gate'; const loot = generateLoot(lootSource); let totalXp = xpGain, totalArks = gate.arksReward; loot.forEach(reward => { if (reward.type === 'xp') totalXp += reward.amount; if (reward.type === 'arks') totalArks += reward.amount; if (reward.type === 'shadow_fragment') playerState.shadowFragments += reward.amount; if (reward.type === 'mystery_box') playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); }); updateWeeklyChallengeProgress(1, 'gate_completions'); gainRewards(totalXp, totalArks); addSystemLog(`O Portão '${gate.name}' foi limpo. Recompensas: ${totalXp} XP, ${totalArks} Arks.`); if (gate.isBoss) { attemptShadowExtraction(gate); } showScreen('gates-screen'); updateUI(); saveGameState(); }

function gainRewards(xp, arks) { const buffedRewards = applyShadowBuffs({ xp, arks }); const finalXp = buffedRewards.xp; const finalArks = buffedRewards.arks; playerState.xp += finalXp; playerState.arks += finalArks; playerState.rankPoints += finalXp; showFloatingText(document.getElementById('xp-bar'), finalXp, 'xp'); showFloatingText(document.getElementById('arks-bar'), finalArks, 'arks'); const leveledUp = checkForLevelUp(), rankedUp = checkForRankUp(); if(leveledUp) { showCelebration("NÍVEL ALCANÇADO!", `Parabéns, Hunter! Você atingiu o Nível ${playerState.level}.`); } if(rankedUp) { showCelebration("PROMOÇÃO DE RANK!", `Sua força foi reavaliada. Você é digno de um novo rank.`, true); } saveGameState(); }
function checkForLevelUp() { let leveledUp = false; while (playerState.xp >= playerState.xpToNextLevel) { playerState.xp -= playerState.xpToNextLevel; playerState.level++; playerState.xpToNextLevel = Math.floor(playerState.xpToNextLevel * 1.5); addSystemLog(`[SISTEMA] Nível ${playerState.level} alcançado.`); leveledUp = true; } return leveledUp; }
function checkForRankUp() { const currentRankIndex = RANKS.indexOf(playerState.rank); if (currentRankIndex < RANKS.length - 1) { const requiredPointsForNextRank = (currentRankIndex + 1) * 500; if (playerState.rankPoints >= requiredPointsForNextRank) { playerState.rank = RANKS[currentRankIndex + 1]; addSystemLog(`[SISTEMA] Promovido para Hunter Rank ${playerState.rank}.`); return true; } } return false; }
function attemptShadowExtraction(gate) { let extractionChance = 0.5; if (playerState.shadowFragments >= 10) { extractionChance = 1.0; playerState.shadowFragments -= 10; addSystemLog("[SISTEMA] 10 Fragmentos de Sombra usados para garantir a extração."); } if (Math.random() < extractionChance) { const possibleShadows = SHADOWS_DATA.filter(s => s.source === gate.id); if (possibleShadows.length > 0) { const extractedShadow = possibleShadows[Math.floor(Math.random() * possibleShadows.length)]; if (!playerState.shadowArmy.find(s => s.id === extractedShadow.id)) { playerState.shadowArmy.push(extractedShadow); addSystemLog(`[SISTEMA] Extração bem-sucedida! A Sombra de '${extractedShadow.name}' se juntou ao seu exército.`); } else { addSystemLog("[SISTEMA] A essência do monstro era fraca. Nenhuma sombra foi extraída."); } } } else { addSystemLog("[SISTEMA] A extração falhou. O monstro não tinha alma suficiente."); } }
function updateShadowArmyUI() { const shadowList = document.getElementById('shadow-army-list'); shadowList.innerHTML = ''; if (playerState.shadowArmy.length === 0) { shadowList.innerHTML = '<p>Nenhuma sombra no exército ainda. Derrote Portões Chefe para tentar a extração.</p>'; return; } playerState.shadowArmy.forEach(shadow => { const isEquipped = shadow.id === playerState.equippedShadowId; const shadowDiv = document.createElement('div'); shadowDiv.className = `shadow-item ${isEquipped ? 'equipped' : ''} clickable`; shadowDiv.innerHTML = `<i class="fas ${shadow.icon}" style="font-size: 2em; color: var(--primary-color);"></i><strong>${shadow.name}</strong><p>${shadow.bonus}</p>`; shadowDiv.onclick = () => equipShadow(shadow.id); shadowList.appendChild(shadowDiv); }); }

const awakeningTexts = [ "Você se sente fraco. Inútil. O mundo dos Hunters é cruel para os de baixo rank.", "Mas algo dentro de você desperta. Uma voz. Uma interface digital preenche sua visão.", "[SISTEMA] Condições atendidas. O Hunter está despertando.", "[SISTEMA] Bem-vindo, Hunter. Eu sou o seu guia. Eu farei de você o mais forte.", "Sua jornada começa agora. Complete Missões, limpe Portões e torne-se uma lenda.", "Vamos começar com uma Missão simples. Boa sorte, Hunter." ];
function showAwakening() { document.getElementById('awakening-overlay').style.display = 'flex'; nextAwakeningStep(); }
function nextAwakeningStep() { if (awakeningStep < awakeningTexts.length) { const textElement = document.getElementById('awakening-text'); textElement.style.opacity = 0; setTimeout(() => { textElement.textContent = awakeningTexts[awakeningStep]; textElement.style.opacity = 1; awakeningStep++; }, 300); } else { document.getElementById('awakening-overlay').style.display = 'none'; initializeApp(); } }document.addEventListener('DOMContentLoaded', () => {
    if (!localStorage.getItem('arisePlayerState')) { showAwakening(); } else { initializeApp(); }
});

// --- ESTADO GLOBAL DO JOGO ---
let playerState = {
    name: 'Hunter', level: 1, xp: 0, xpToNextLevel: 100, arks: 0, rank: 'E', rankPoints: 0,
    rankPointsToNext: 500, completedMissionsToday: [], completedGatesToday: [], shadowArmy: [],
    equippedWeapon: null, equippedSkill: null, xpMultiplier: 1, shadowFragments: 0,
    dailyMissions: [], inventory: [],
    // NOVAS PROPRIEDADES DINÂMICAS
    weeklyChallenge: null, lastWeeklyResetDate: null, equippedShadowId: null,
};

let gateTimer = null, gateSeconds = 0, awakeningStep = 0;

// --- BANCOS DE DADOS DA IA (EXPANDIDOS) ---
const EXERCISE_DB = [ { id: 'pushups', name: 'Flexões', unit: 'reps', icon: 'fa-hand-rock' }, { id: 'squats', name: 'Agachamentos', unit: 'reps', icon: 'fa-dumbbell' }, { id: 'plank', name: 'Prancha', unit: 'segundos', icon: 'fa-stopwatch' }, { id: 'jumping_jacks', name: 'Polichinelos', unit: 'reps', icon: 'fa-child' }, { id: 'lunges', name: 'Afundos', unit: 'reps', icon: 'fa-walking' }, { id: 'run', name: 'Corrida Leve', unit: 'minutos', icon: 'fa-running' }, ];
const MISSION_TEMPLATES = [ { type: 'reps', baseValue: 10, variance: 5, xpBase: 15, arksBase: 8 }, { type: 'time', baseValue: 30, variance: 15, xpBase: 10, arksBase: 5 }, ];
const LOOT_TABLES = { mission: [{ type: 'arks', min: 5, max: 15, chance: 0.7 }, { type: 'xp', min: 10, max: 25, chance: 0.6 }, { type: 'shadow_fragment', amount: 1, chance: 0.05 }, { type: 'mystery_box', amount: 1, chance: 0.02 }], gate: [{ type: 'arks', min: 20, max: 40, chance: 0.8 }, { type: 'xp', min: 40, max: 80, chance: 0.9 }, { type: 'shadow_fragment', amount: 1, chance: 0.1 }, { type: 'mystery_box', amount: 1, chance: 0.05 }], boss: [{ type: 'arks', min: 80, max: 120, chance: 1.0 }, { type: 'xp', min: 180, max: 250, chance: 1.0 }, { type: 'shadow_fragment', amount: 3, chance: 0.5 }, { type: 'mystery_box', amount: 2, chance: 0.2 }], };
const GATES_DATA = [ { id: 'g1', name: 'Portão de Treinamento: Corpo Inferior', xpReward: 50, arksReward: 25, description: 'Foco em pernas e glúteos.', difficulty: 'Fácil', icon: 'fa-shoe-prints' }, { id: 'g2', name: 'Portão de Treinamento: Força Bruta', xpReward: 60, arksReward: 30, description: 'Foco em peito e costas.', difficulty: 'Médio', icon: 'fa-fist-raised' }, { id: 'gBoss', name: 'Portão Chefe: Monarca do HIIT', xpReward: 200, arksReward: 100, description: 'Treino intervalado de alta intensidade.', difficulty: 'Difícil', isBoss: true, icon: 'fa-skull-crossbones' }, ];
const SHADOWS_DATA = [
    { id: 's1', name: 'Soldado', bonus: '+2% XP em Missões', source: 'g1', icon: 'fa-shield-alt', bonusType: 'xp_percentage', bonusValue: 0.02 },
    { id: 's2', name: 'Igris', bonus: '+5% Arks em Portões', source: 'gBoss', icon: 'fa-khanda', bonusType: 'arks_percentage', bonusValue: 0.05 },
];
const SHOP_ITEMS = [ { id: 'potion1', name: 'Poção de EXP Pequena', cost: 50, effect: () => { gainRewards(100, 0); }, description: 'Ganha 100 XP instantaneamente.', icon: 'fa-flask' }, { id: 'potion2', name: 'Poção de Arks Pequena', cost: 25, effect: () => { gainRewards(0, 50); }, description: 'Ganha 50 Arks instantaneamente.', icon: 'fa-gem' }, { id: 'boost1', name: 'Boost de Treinamento (1 uso)', cost: 150, effect: () => { playerState.xpMultiplier = 2; addSystemLog("[SISTEMA] Boost de 2x XP ativado para o próximo Portão."); }, description: 'Dobra o XP do próximo Portão concluído.', icon: 'fa-rocket' }, ];
const WEEKLY_CHALLENGE_TEMPLATES = [ { type: 'total_reps', target: 500, description: 'Complete 500 repetições (Flexões, Agachamentos, etc.) esta semana.', reward: { type: 'shadow', id: 's1' } }, { type: 'total_time', target: 120, description: 'Acumule 120 minutos de treino (Corrida, Prancha, etc.) esta semana.', reward: { type: 'arks', amount: 300 } }, { type: 'gate_completions', target: 10, description: 'Limpe 10 Portões esta semana.', reward: { type: 'mystery_box', amount: 5 } }, ];
const EVENT_GATE_DATA = { name: 'Portão de Evento: Dimensão Fissurada', description: 'Uma anomalia espaço-temporal! Dificuldade extrema, recompensas lendárias.', xpReward: 350, arksReward: 200, difficulty: 'Impossível', icon: 'fa-vortex', isBoss: true };

// --- FUNÇÕES PRINCIPAIS ---
function initializeApp() { loadGameState(); if (playerState.dailyMissions.length === 0) { generateDailyMissionsAI(); } if (playerState.weeklyChallenge === null) { generateWeeklyChallenge(); } checkForWeeklyReset(); updateUI(); updateMissionUI(); updateWeeklyChallengeUI(); generateGates(); generateShopItems(); addSystemLog("[SISTEMA] O Hunter está online."); }
function saveGameState() { localStorage.setItem('arisePlayerState', JSON.stringify(playerState)); }
function loadGameState() { const savedState = localStorage.getItem('arisePlayerState'); if (savedState) { try { playerState = { ...playerState, ...JSON.parse(savedState) }; } catch (e) { console.error("Failed to load saved state, resetting.", e); } } checkForDailyReset(); }
function checkForDailyReset() { const lastPlayed = localStorage.getItem('ariseLastPlayedDate'), today = new Date().toDateString(); if (lastPlayed !== today) { playerState.completedMissionsToday = []; playerState.completedGatesToday = []; playerState.dailyMissions = []; localStorage.setItem('ariseLastPlayedDate', today); addSystemLog("[SISTEMA] Novo dia detectado. A IA está gerando novas oportunidades.", true); } }
function checkForWeeklyReset() { const now = new Date(); const lastReset = playerState.lastWeeklyResetDate ? new Date(playerState.lastWeeklyResetDate) : null; if (!lastReset || now.getDay() < lastReset.getDay() || now.getDay() === 1) { playerState.weeklyChallenge = null; playerState.lastWeeklyResetDate = now.toDateString(); generateWeeklyChallenge(); addSystemLog("[SISTEMA] Nova semana, novo Desafio Semanal disponível!", true); } }

// --- UI ---
function updateUI() {
    document.getElementById('player-name').textContent = playerState.name; document.getElementById('player-level').textContent = playerState.level; document.getElementById('player-rank').textContent = playerState.rank;
    document.getElementById('xp-text').textContent = `${playerState.xp} / ${playerState.xpToNextLevel}`; document.getElementById('arks-text').textContent = playerState.arks;
    const xpPercent = (playerState.xp / playerState.xpToNextLevel) * 100; document.getElementById('xp-bar').style.width = `${xpPercent}%`;
    document.getElementById('fragments-text').textContent = `${playerState.shadowFragments} / 10`; const fragmentsPercent = (playerState.shadowFragments / 10) * 100; document.getElementById('fragments-bar').style.width = `${fragmentsPercent}%`;
    updateRankProgressRing();
    document.getElementById('daily-mission-count').textContent = playerState.completedMissionsToday.length; document.getElementById('total-mission-count').textContent = playerState.dailyMissions.length; document.getElementById('daily-gate-count').textContent = playerState.completedGatesToday.length;
    document.getElementById('equipped-weapon').textContent = playerState.equippedWeapon ? playerState.equippedWeapon.name : 'Nenhuma'; document.getElementById('equipped-skill').textContent = playerState.equippedSkill ? playerState.equippedSkill.name : 'Nenhuma';
    const equippedShadow = playerState.shadowArmy.find(s => s.id === playerState.equippedShadowId);
    if (equippedShadow) { document.getElementById('equipped-shadow-name').textContent = equippedShadow.name; document.getElementById('equipped-shadow-bonus').textContent = `Bônus Ativo: ${equippedShadow.bonus}`; } else { document.getElementById('equipped-shadow-name').textContent = 'Nenhuma'; document.getElementById('equipped-shadow-bonus').textContent = 'Escolha uma sombra para receber seu bônus.'; }
    updateShadowArmyUI();
}
function updateRankProgressRing() { const currentRankIndex = RANKS.indexOf(playerState.rank); playerState.rankPointsToNext = (currentRankIndex + 1) * 500; const rankPercent = Math.min((playerState.rankPoints / playerState.rankPointsToNext) * 100, 100); const circle = document.getElementById('rank-progress-ring-fill'), radius = circle.r.baseVal.value, circumference = radius * 2 * Math.PI; const offset = circumference - (rankPercent / 100) * circumference; circle.style.strokeDasharray = `${circumference} ${circumference}`; circle.style.strokeDashoffset = offset; document.getElementById('rank-percent').textContent = `${Math.floor(rankPercent)}%`; }
function showScreen(screenId) { document.querySelectorAll('.screen').forEach(s => s.classList.remove('active')); document.getElementById(screenId).classList.add('active'); }
function addSystemLog(message, isGlitch = false) { const log = document.getElementById('system-log'), p = document.createElement('p'); if(isGlitch) p.classList.add('glitch'); p.textContent = `> ${message}`; log.appendChild(p); log.scrollTop = log.scrollHeight; }
function showModal(title, body, footerContent) { document.getElementById('modal-title').innerHTML = title; document.getElementById('modal-body').innerHTML = body; document.getElementById('modal-footer').innerHTML = footerContent; document.getElementById('modal-container').style.display = 'block'; }
function hideModal() { document.getElementById('modal-container').style.display = 'none'; }
function showCelebration(title, message, isRankUp = false) { document.getElementById('celebration-title').textContent = title; document.getElementById('celebration-message').textContent = message; document.getElementById('celebration-overlay').style.display = 'flex'; if (isRankUp) { document.getElementById('new-rank-display').textContent = `Rank ${playerState.rank}`; document.getElementById('celebration-rank-up').style.display = 'block'; } else { document.getElementById('celebration-rank-up').style.display = 'none'; } }
function hideCelebration() { document.getElementById('celebration-overlay').style.display = 'none'; }
function showFloatingText(targetElement, text, type) { const floater = document.createElement('div'); floater.className = `floating-text ${type}`; floater.textContent = `+${text}`; const rect = targetElement.getBoundingClientRect(); floater.style.left = `${rect.left + rect.width / 2}px`; floater.style.top = `${rect.top}px`; document.body.appendChild(floater); setTimeout(() => floater.remove(), 2000); }

// --- SISTEMA DINÂMICO: DESAFIO SEMANAL ---
function generateWeeklyChallenge() { const template = WEEKLY_CHALLENGE_TEMPLATES[Math.floor(Math.random() * WEEKLY_CHALLENGE_TEMPLATES.length)]; playerState.weeklyChallenge = { ...template, progress: 0, claimed: false, }; saveGameState(); }
function updateWeeklyChallengeUI() { if (!playerState.weeklyChallenge) return; const challenge = playerState.weeklyChallenge; document.getElementById('weekly-challenge-description').textContent = challenge.description; const progressPercent = (challenge.progress / challenge.target) * 100; document.getElementById('weekly-challenge-progress').style.width = `${progressPercent}%`; document.getElementById('weekly-challenge-progress-text').textContent = `${challenge.progress} / ${challenge.target}`; const claimButton = document.getElementById('claim-weekly-reward'); if (challenge.progress >= challenge.target && !challenge.claimed) { claimButton.style.display = 'block'; } else { claimButton.style.display = 'none'; } }
function updateWeeklyChallengeProgress(amount, type) { if (!playerState.weeklyChallenge || playerState.weeklyChallenge.claimed) return; if (playerState.weeklyChallenge.type === type) { playerState.weeklyChallenge.progress += amount; if (playerState.weeklyChallenge.progress > playerState.weeklyChallenge.target) { playerState.weeklyChallenge.progress = playerState.weeklyChallenge.target; } updateWeeklyChallengeUI(); } }
function claimWeeklyReward() { const reward = playerState.weeklyChallenge.reward; if (reward.type === 'arks') { playerState.arks += reward.amount; } if (reward.type === 'mystery_box') { playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); } if (reward.type === 'shadow') { const shadowData = SHADOWS_DATA.find(s => s.id === reward.id); if (!playerState.shadowArmy.find(s => s.id === reward.id)) { playerState.shadowArmy.push(shadowData); addSystemLog(`[SISTEMA] Recompensa do Desafio Semanal recebida! A Sombra de '${shadowData.name}' se juntou ao seu exército.`); } else { playerState.arks += 200; addSystemLog(`[SISTEMA] Recompensa do Desafio Semanal recebida! 200 Arks concedidos.`); } } playerState.weeklyChallenge.claimed = true; updateUI(); updateWeeklyChallengeUI(); saveGameState(); }

// --- SISTEMA DINÂMICO: SINERGIA DE SOMBRAS ---
function equipShadow(shadowId) { if (playerState.shadowArmy.find(s => s.id === shadowId)) { playerState.equippedShadowId = shadowId; addSystemLog(`[SISTEMA] Sombra equipada. Bônus ativo.`); updateUI(); updateShadowArmyUI(); } }
function applyShadowBuffs(rewards) { const equippedShadow = playerState.shadowArmy.find(s => s.id === playerState.equippedShadowId); if (!equippedShadow) return rewards; let { xp, arks } = rewards; if (equippedShadow.bonusType === 'xp_percentage') { xp = Math.floor(xp * (1 + equippedShadow.bonusValue)); } if (equippedShadow.bonusType === 'arks_percentage') { arks = Math.floor(arks * (1 + equippedShadow.bonusValue)); } return { xp, arks }; }

// --- SISTEMA DINÂMICO: PORTÕES DE EVENTO ---
function generateGates() { const gateList = document.getElementById('gate-list'); gateList.innerHTML = ''; if (Math.random() < 0.1) { const eventGate = { ...EVENT_GATE_DATA, id: 'event_gate_' + Date.now() }; const gateDiv = document.createElement('div'); gateDiv.className = 'gate-item card event-gate'; gateDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${eventGate.icon}"></i> ${eventGate.name} <span style="color: var(--warning-color)">(${eventGate.difficulty})</span></h4><p>${eventGate.description}</p><small><i class="fas fa-star"></i> ${eventGate.xpReward} XP | <i class="fas fa-gem"></i> ${eventGate.arksReward} Arks</small></div><button onclick="enterGate('${eventGate.id}')">Entrar</button>`; gateList.appendChild(gateDiv); } GATES_DATA.forEach(gate => { const isCompleted = playerState.completedGatesToday.includes(gate.id); const gateDiv = document.createElement('div'); gateDiv.className = 'gate-item card'; if (gate.isBoss) gateDiv.style.borderColor = 'var(--danger-color)'; gateDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${gate.icon}"></i> ${gate.name} <span style="color: ${gate.difficulty === 'Fácil' ? 'var(--success-color)' : gate.difficulty === 'Médio' ? 'var(--warning-color)' : 'var(--danger-color)'}">(${gate.difficulty})</span></h4><p>${gate.description}</p><small><i class="fas fa-star"></i> ${gate.xpReward} XP | <i class="fas fa-gem"></i> ${gate.arksReward} Arks</small></div><button onclick="enterGate('${gate.id}')" ${isCompleted ? 'disabled' : ''}>Entrar</button>`; gateList.appendChild(gateDiv); }); }

// --- SISTEMA DINÂMICO: OFERTA DIÁRIA DA LOJA ---
function generateShopItems() { const shopList = document.getElementById('shop-items'); shopList.innerHTML = ''; const dailyDealIndex = Math.floor(Math.random() * SHOP_ITEMS.length); SHOP_ITEMS.forEach((item, index) => { const isDailyDeal = index === dailyDealIndex; const finalCost = isDailyDeal ? Math.floor(item.cost * 0.75) : item.cost; const canAfford = playerState.arks >= finalCost; const itemDiv = document.createElement('div'); itemDiv.className = `shop-item card ${isDailyDeal ? 'daily-deal' : ''}`; itemDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${item.icon}"></i> ${item.name}</h4><p>${item.description}</p><small><i class="fas fa-gem"></i> Custo: <s>${item.cost}</s> ${finalCost} Arks ${isDailyDeal ? '(25% OFF)' : ''}</small></div><button onclick="confirmItemPurchase('${item.id}', ${finalCost})" ${!canAfford ? 'disabled' : ''}>Comprar</button>`; shopList.appendChild(itemDiv); }); }
function confirmItemPurchase(itemId, cost) { const item = SHOP_ITEMS.find(i => i.id === itemId); const onConfirm = () => { playerState.arks -= cost; item.effect(); updateUI(); generateShopItems(); addSystemLog(`[SISTEMA] Você comprou '${item.name}'.`); hideModal(); }; showModal(`Confirmar Compra: ${item.name}`, `<p>Tem certeza que deseja comprar <strong>${item.name}</strong> por <strong>${cost} Arks</strong>?</p>`, `<button onclick="hideModal()">Cancelar</button><button class="btn-shop" onclick="onConfirm()" style="margin-left: 10px;">Comprar</button>`); }

// --- LÓGICA DE MISSÕES E PORTÕES (ATUALIZADA) ---
function generateDailyMissionsAI() { if (playerState.dailyMissions.length > 0) return; const missionCount = 4; for (let i = 0; i < missionCount; i++) { const template = MISSION_TEMPLATES[Math.floor(Math.random() * MISSION_TEMPLATES.length)]; const exercise = EXERCISE_DB[Math.floor(Math.random() * EXERCISE_DB.length)]; const levelScaling = 1 + (playerState.level * 0.1); let targetValue = Math.floor((template.baseValue + Math.floor(Math.random() * template.variance)) * levelScaling); let xpReward = Math.floor((template.xpBase + (targetValue * 0.1)) * levelScaling); let arksReward = Math.floor((template.arksBase + (targetValue * 0.05)) * levelScaling); const isSpecial = Math.random() < 0.1; if (isSpecial) { targetValue *= 2; xpReward *= 2.5; arksReward *= 2; } playerState.dailyMissions.push({ id: `ai_mission_${Date.now()}_${i}`, name: `${isSpecial ? '[S] ' : ''}${exercise.name}`, description: `Complete ${targetValue} ${exercise.unit}.`, xpReward: Math.floor(xpReward), arksReward: Math.floor(arksReward), icon: exercise.icon, isSpecial: isSpecial }); } saveGameState(); }
function generateLoot(source) { const table = LOOT_TABLES[source]; if (!table) return []; const rewards = []; table.forEach(item => { if (Math.random() < item.chance) { let amount = item.amount; if (item.type === 'arks' || item.type === 'xp') { amount = Math.floor(Math.random() * (item.max - item.min + 1)) + item.min; } rewards.push({ type: item.type, amount: amount }); } }); return rewards; }
function updateMissionUI() { const missionList = document.getElementById('mission-list'); missionList.innerHTML = ''; if (playerState.dailyMissions.length === 0) { missionList.innerHTML = '<p>A IA está preparando suas missões para o dia.</p>'; return; } playerState.dailyMissions.forEach(mission => { const isCompleted = playerState.completedMissionsToday.includes(mission.id); const missionDiv = document.createElement('div'); missionDiv.className = `mission-item card ${isCompleted ? 'completed' : ''} ${mission.isSpecial ? 'special-mission' : ''}`; missionDiv.innerHTML = `<div class="item-info"><h4><i class="fas ${mission.icon}"></i> ${mission.name}</h4><p>${mission.description}</p><small><i class="fas fa-star"></i> ${mission.xpReward} XP | <i class="fas fa-gem"></i> ${mission.arksReward} Arks</small></div><button onclick="completeMission('${mission.id}')" ${isCompleted ? 'disabled' : ''}>Completar</button>`; missionList.appendChild(missionDiv); }); }
function completeMission(missionId) { if (playerState.completedMissionsToday.includes(missionId)) return; const mission = playerState.dailyMissions.find(m => m.id === missionId); const onConfirm = () => { playerState.completedMissionsToday.push(mission.id); const loot = generateLoot('mission'); let totalXp = mission.xpReward, totalArks = mission.arksReward; loot.forEach(reward => { if (reward.type === 'xp') totalXp += reward.amount; if (reward.type === 'arks') totalArks += reward.amount; if (reward.type === 'shadow_fragment') playerState.shadowFragments += reward.amount; if (reward.type === 'mystery_box') playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); }); if (mission.unit === 'reps') updateWeeklyChallengeProgress(parseInt(mission.description.match(/\d+/)[0]), 'total_reps'); if (mission.unit === 'minutos' || mission.unit === 'segundos') updateWeeklyChallengeProgress(parseInt(mission.description.match(/\d+/)[0]), 'total_time'); gainRewards(totalXp, totalArks); addSystemLog(`Missão '${mission.name}' concluída. Recompensas: ${totalXp} XP, ${totalArks} Arks, e outras recompensas da IA.`); updateUI(); updateMissionUI(); if (playerState.completedMissionsToday.length === playerState.dailyMissions.length) { document.getElementById('claim-daily-reward').style.display = 'block'; } hideModal(); }; showModal(`Confirmar Missão: ${mission.name}`, `<p>Você realizou a tarefa: <strong>${mission.description}</strong>?</p>`, `<button onclick="hideModal()">Ainda não</button><button class="btn-reward" onclick="onConfirm()" style="margin-left: 10px;">Sim, Concluir!</button>`); }
function claimDailyReward() { gainRewards(50, 25); addSystemLog("[SISTEMA] Todas as missões diárias concluídas. Bônus concedido."); document.getElementById('claim-daily-reward').style.display = 'none'; saveGameState(); }
function enterGate(gateId) { let gate; if (gateId.startsWith('event_gate')) { gate = EVENT_GATE_DATA; } else { gate = GATES_DATA.find(g => g.id === gateId); } if (playerState.completedGatesToday.includes(gate.id)) { showModal("Portão Já Conquistado", `<p>Você já limpou este portão hoje. Volte amanhã para um novo desafio.</p>`, `<button onclick="hideModal()">Entendido</button>`); return; } showScreen('gate-active-screen'); document.getElementById('active-gate-name').textContent = gate.name; document.getElementById('active-gate-description').textContent = gate.description; startGateTimer(); }
function startGateTimer() { gateSeconds = 0; updateGateTimerDisplay(); gateTimer = setInterval(() => { gateSeconds++; updateGateTimerDisplay(); }, 1000); }
function updateGateTimerDisplay() { const minutes = Math.floor(gateSeconds / 60), secs = gateSeconds % 60; document.getElementById('gate-timer').textContent = `${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`; }
function completeActiveGate() { clearInterval(gateTimer); const gateName = document.getElementById('active-gate-name').textContent; let gate; if (gateName.includes('Dimensão Fissurada')) { gate = EVENT_GATE_DATA; } else { gate = GATES_DATA.find(g => g.name === gateName); } playerState.completedGatesToday.push(gate.id); let xpGain = gate.xpReward; if (playerState.xpMultiplier > 1) { xpGain *= playerState.xpMultiplier; playerState.xpMultiplier = 1; addSystemLog("[SISTEMA] Boost de XP consumido.", true); } const lootSource = gate.isBoss ? 'boss' : 'gate'; const loot = generateLoot(lootSource); let totalXp = xpGain, totalArks = gate.arksReward; loot.forEach(reward => { if (reward.type === 'xp') totalXp += reward.amount; if (reward.type === 'arks') totalArks += reward.amount; if (reward.type === 'shadow_fragment') playerState.shadowFragments += reward.amount; if (reward.type === 'mystery_box') playerState.inventory = (playerState.inventory || []).concat(Array(reward.amount).fill({name: 'Caixa Misteriosa'})); }); updateWeeklyChallengeProgress(1, 'gate_completions'); gainRewards(totalXp, totalArks); addSystemLog(`O Portão '${gate.name}' foi limpo. Recompensas: ${totalXp} XP, ${totalArks} Arks, e outras recompensas da IA.`); if (gate.isBoss) { attemptShadowExtraction(gate); } showScreen('gates-screen'); updateUI(); saveGameState(); }

// --- LÓGICA DE RECOMPENSAS E PROGRESSÃO (ATUALIZADA) ---
const RANKS = ['E', 'D', 'C', 'B', 'A', 'S'];
function gainRewards(xp, arks) { const buffedRewards = applyShadowBuffs({ xp, arks }); const finalXp = buffedRewards.xp; const finalArks = buffedRewards.arks; playerState.xp += finalXp; playerState.arks += finalArks; playerState.rankPoints += finalXp; showFloatingText(document.getElementById('xp-bar'), finalXp, 'xp'); showFloatingText(document.getElementById('arks-bar'), finalArks, 'arks'); const leveledUp = checkForLevelUp(), rankedUp = checkForRankUp(); if(leveledUp) { showCelebration("NÍVEL ALCANÇADO!", `Parabéns, Hunter! Você atingiu o Nível ${playerState.level}.`); } if(rankedUp) { showCelebration("PROMOÇÃO DE RANK!", `Sua força foi reavaliada. Você é digno de um novo rank.`, true); } saveGameState(); }
function checkForLevelUp() { let leveledUp = false; while (playerState.xp >= playerState.xpToNextLevel) { playerState.xp -= playerState.xpToNextLevel; playerState.level++; playerState.xpToNextLevel = Math.floor(playerState.xpToNextLevel * 1.5); addSystemLog(`[SISTEMA] Nível ${playerState.level} alcançado.`); leveledUp = true; } return leveledUp; }
function checkForRankUp() { const currentRankIndex = RANKS.indexOf(playerState.rank); if (currentRankIndex < RANKS.length - 1) { const requiredPointsForNextRank = (currentRankIndex + 1) * 500; if (playerState.rankPoints >= requiredPointsForNextRank) { playerState.rank = RANKS[currentRankIndex + 1]; addSystemLog(`[SISTEMA] Promovido para Hunter Rank ${playerState.rank}.`); return true; } } return false; }
function attemptShadowExtraction(gate) { let extractionChance = 0.5; if (playerState.shadowFragments >= 10) { extractionChance = 1.0; playerState.shadowFragments -= 10; addSystemLog("[SISTEMA] 10 Fragmentos de Sombra usados para garantir a extração."); } if (Math.random() < extractionChance) { const possibleShadows = SHADOWS_DATA.filter(s => s.source === gate.id); if (possibleShadows.length > 0) { const extractedShadow = possibleShadows[Math.floor(Math.random() * possibleShadows.length)]; if (!playerState.shadowArmy.find(s => s.id === extractedShadow.id)) { playerState.shadowArmy.push(extractedShadow); addSystemLog(`[SISTEMA] Extração bem-sucedida! A Sombra de '${extractedShadow.name}' se juntou ao seu exército.`); } else { addSystemLog("[SISTEMA] A essência do monstro era fraca. Nenhuma sombra foi extraída."); } } } else { addSystemLog("[SISTEMA] A extração falhou. O monstro não tinha alma suficiente."); } }
function updateShadowArmyUI() { const shadowList = document.getElementById('shadow-army-list'); shadowList.innerHTML = ''; if (playerState.shadowArmy.length === 0) { shadowList.innerHTML = '<p>Nenhuma sombra no exército ainda. Derrote Portões Chefe para tentar a extração.</p>'; return; } playerState.shadowArmy.forEach(shadow => { const isEquipped = shadow.id === playerState.equippedShadowId; const shadowDiv = document.createElement('div'); shadowDiv.className = `shadow-item ${isEquipped ? 'equipped' : ''} clickable`; shadowDiv.innerHTML = `<i class="fas ${shadow.icon}" style="font-size: 2em; color: var(--primary-color);"></i><strong>${shadow.name}</strong><p>${shadow.bonus}</p>`; shadowDiv.onclick = () => equipShadow(shadow.id); shadowList.appendChild(shadowDiv); }); }

// --- AWAKENING ONBOARDING ---
const awakeningTexts = [ "Você se sente fraco. Inútil. O mundo dos Hunters é cruel para os de baixo rank.", "Mas algo dentro de você desperta. Uma voz. Uma interface digital preenche sua visão.", "[SISTEMA] Condições atendidas. O Hunter está despertando.", "[SISTEMA] Bem-vindo, Hunter. Eu sou o seu guia. Eu farei de você o mais forte.", "Sua jornada começa agora. Complete Missões, limpe Portões e torne-se uma lenda.", "Vamos começar com uma Missão simples. Boa sorte, Hunter." ];
function showAwakening() { document.getElementById('awakening-overlay').style.display = 'flex'; nextAwakeningStep(); }
function nextAwakeningStep() { if (awakeningStep < awakeningTexts.length) { const textElement = document.getElementById('awakening-text'); textElement.style.opacity = 0; setTimeout(() => { textElement.textContent = awakeningTexts[awakeningStep]; textElement.style.opacity = 1; awakeningStep++; }, 300); } else { document.getElementById('awakening-overlay').style.display = 'none'; initializeApp(); } }
